version: '3.8'
services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_DB=manager_personnel_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    build:
      context: ./../
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '8080:8080'

  nginx:
    image: nginx:1.23.3
    ports:
      - '80:80'
    volumes:
      - ../build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
volumes:
  db:
  # docker compose -p minhvan-frontend-backend-postgresql up -d