version: '3.8'
services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_DB=n_news_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'